[config]
contrast = 1

# [templates.yazi]
# input_path = './templates/yazi-theme.toml'
# output_path = '~/.config/yazi/theme.toml'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.neovim]
input_path = './templates/template.lua'
output_path = '~/.config/nvim/colors/matugen.lua'

[templates.firefox-website-colors]
input_path = "./templates/firefox-colors.css"
output_path = "~/.config/mozilla/firefox/5f7rFG8x.Profile 1/chrome/colors.css"

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.quickshell]
input_path = './templates/quickshell.qml'
output_path = '~/.config/quickshell/Style/Colors.qml'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.niri]
input_path = './templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.ghostty]
input_path = './templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.kvantum_kvconfig]
input_path = './templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = './templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.mako]
input_path = './templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

