-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#0e1513",
  base01 = "#090f0e",
  base02 = "#171d1b",
  base03 = "#3f4945",
  base04 = "#bfc9c4",
  base05 = "#dee4e0",
  base06 = "#2b322f",
  base07 = "#343b38",

  base08 = "#97bfdd",
  base09 = "#aacbe3",
  base0A = "#b1ccc3",
  base0B = "#85d6c0",
  base0C = "#2a4a5f",
  base0D = "#005143",
  base0E = "#334b45",
  base0F = "#92b8ab",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#005143',
  fg = '#a1f2dc', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#70a8d0',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#89938f',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#aacbe3',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b1ccc3',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#0a6b5a',
})
