-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#191113",
  base01 = "#000000",
  base02 = "#261d1f",
  base03 = "#d2bec1",
  base04 = "#ffffff",
  base05 = "#ffffff",
  base06 = "#000000",
  base07 = "#594d4f",

  base08 = "#ffdfc6",
  base09 = "#ffeddf",
  base0A = "#ffebee",
  base0B = "#ffebee",
  base0C = "#e9ba8e",
  base0D = "#ffabbf",
  base0E = "#dfb9c0",
  base0F = "#ffb8c3",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#ffabbf',
  fg = '#000000', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#ffc293',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#ffebee',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#ffeddf',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#ffebee',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#723445',
})
